<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LT0088970" name="com.form16.qa.testcases.Form16PageTest" tests="7" failures="1" timestamp="26 Jun 2018 09:28:38 GMT" time="17.932" errors="0">
  <testcase name="rightSpinnerTest" time="1.063" classname="com.form16.qa.testcases.Form16PageTest"/>
  <testcase name="form16TabTest" time="0.226" classname="com.form16.qa.testcases.Form16PageTest"/>
  <testcase name="pdfDownloadTest" time="14.605" classname="com.form16.qa.testcases.Form16PageTest">
    <failure type="java.lang.AssertionError" message=" Verification failed: Expected and Actual result do not matched :  expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError:  Verification failed: Expected and Actual result do not matched :  expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.form16.qa.testcases.Form16PageTest.pdfDownloadTest(Form16PageTest.java:103)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- pdfDownloadTest -->
  <testcase name="instructiontabTextTest" time="0.103" classname="com.form16.qa.testcases.Form16PageTest"/>
  <testcase name="leftSpinnerTest" time="0.617" classname="com.form16.qa.testcases.Form16PageTest"/>
  <testcase name="instrcutionTabTest" time="0.403" classname="com.form16.qa.testcases.Form16PageTest"/>
  <testcase name="policyButtonTest" time="0.915" classname="com.form16.qa.testcases.Form16PageTest"/>
</testsuite> <!-- com.form16.qa.testcases.Form16PageTest -->
